import prisma from "../lib/prisma";
import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Footer from "../components/Footer";

import { AppContext } from "../utils/contextState";
import { useState, useContext } from "react";
import { Button } from "@mui/material";
import LoginForm from "../components/forms/LoginForm";
import RegisterForm from "../components/forms/RegisterForm";

//getServerSideProps
export async function getServerSideProps() {
  const users = await prisma.user.findMany();
  return {
    props: {
      initialUsers: users,
    },
  };
}

//main component
export default function Home() {
  const [changeForm, setChangeForm] = useState(true);
  return (
    <>
      <Head>
        <title>CRM app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="root">
        <div className="form-position">
          <Navbar /> {/* good practise? Inside or outside root component?*/}
          <div
            className={
              changeForm
                ? "form-container"
                : "form-container  form-container__expanded"
            }
          >
            {changeForm ? <LoginForm /> : <RegisterForm />}
            <section className="formChangeArea">
              {changeForm ? <p>Have account?</p> : <p>New to In Point?</p>}
              <Button
                onClick={() => setChangeForm(!changeForm)}
                variant="outlined"
                color="success"
                type="submit"
                size="small"
              >
                {changeForm ? "Sign Up" : "Log In"}
              </Button>
            </section>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
}

//Navbar
function Navbar() {
  const router = useRouter();
  console.log(router.pathname);
  return (
    <div className="topnav">
      <Image src="/logo3.png" alt="logo" width="200px" height="52px" />
    </div>
  );
}
