import prisma from "../lib/prisma";
import * as React from "react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Footer from "../components/Footer";
import EntryForms from "../components/forms/EntryForms";

//getServerSideProps
export async function getServerSideProps() {
  const users = await prisma.user.findMany();
  return {
    props: {
      initialUsers: users,
    },
  };
}

//main component
export default function Home() {
  return (
    <>
      <Head>
        <title>CRM app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="root">
        <Navbar /> {/* good practise? Inside or outside root component?*/}
        <div className="form-position">
          <EntryForms />
        </div>
        <Footer />
      </div>
    </>
  );
}

//Navbar
function Navbar() {
  const router = useRouter();
  console.log(router.pathname);
  return (
    <div className="topnav">
      <Image src="/logo3.png" alt="logo" width="200px" height="52px" />
    </div>
  );
}
